POC/api/urls.py
from django.conf.urls import url
from .views import POCAPIView,POCDetailAPIView

urlpatterns=[
    url(r'^$',POCAPIView.as_view()),
    url(r'^(?P<pk>\d+)/$',POCDetailAPIView.as_view())
]

POC/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.PersonListView.as_view(), name='person_changelist'),
    url(r'^create/$', views.PersonCreateView.as_view(), name='person_add'),
    url(r'^(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='person_detail'),
    url(r'^update/(?P<pk>\d+)/$', views.PersonUpdateView.as_view(), name='person_change'),
    url(r'^delete/(?P<pk>\d+)/$', views.PersonDeleteView.as_view(), name='person_delete'),
    url(r'^search/$', views.SearchResultsView.as_view(), name='search_results'),
    url(r'^home/$', views.HomePageView.as_view(), name='home'),
    url(r'^ajax/load-cities/$', views.load_cities, name='ajax_load_cities'),
    ]

blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns= [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('POC.urls')),
    # url(r'^api/poc/',include('POC.api.urls')),
    url(r'^$', user_views.register, name='register'),
    url('profile/', user_views.profile, name='profile'),
    url('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

POC/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
from django.urls import reverse


# Create your models here.

class Country(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class City(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Registration(models.Model):
    APPROVE_CHOICES = (
        ('', 'Choose...'),
        ('Under-Process', 'Under-Process'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected'),
    )
    BUSINESS_TYPES = (
    ('', 'Choose...'),
    ('Vehicle Loan', 'Vehicle Loan'),
    ('House Loan', 'House Loan'),
    ('Agriculture Loan', 'Agriculture Loan')
    )
    GENDER_CHOICES = (
        ('', 'Choose...'),
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other','Other'),
    )


    name=models.CharField(max_length=80)
    age=models.IntegerField()
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    date_posted = models.DateTimeField(default=timezone.now)
    address=models.TextField(default='')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    zip=models.age=models.IntegerField(null=True)
    amount_required = models.IntegerField(null=True,blank=True)
    business_type = models.CharField(max_length=20, choices=BUSINESS_TYPES,null=True,blank=True)
    phone = models.CharField(max_length=32,null=True,blank=True)
    Approve_Reject=models.CharField(max_length=20, choices=APPROVE_CHOICES,null=True,blank=True,default='Under-Process')


    def __str__(self):
        return self.name





    def get_absolute_url(self):
        return reverse('person_changelist')

POC/forms.py
from django import forms
from .models import Registration, City



class PersonForm(forms.ModelForm):
    # name = forms.CharField(disabled=True)
    class Meta:
        model = Registration
        fields = ['name','age','gender','country','city','zip','address','amount_required','business_type','phone','Approve_Reject']




    def __init__(self, *args, **kwargs):
        # super().__init__(*args, **kwargs)
        super(PersonForm, self).__init__(*args,**kwargs)
        self.fields['city'].queryset = City.objects.none()





        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

POC/api/views.py
from POC.models import Registration
from .serializers import POCSerializer
from rest_framework import serializers
from rest_framework import generics
from rest_framework import mixins

class POCAPIView(mixins.CreateModelMixin,generics.ListAPIView):
    permission_classes=[]
    authentication_classes=[]
    serializer_class=POCSerializer

    def get_queryset(self):
        qs=Registration.objects.all()
        query=self.request.GET.get('q')
        if query is not None:
            qs=qs.objects.filter(content_icontains=query)
        return qs

    def post(self,request,*args,**kwargs):
        return self.create(request,*args,**kwargs)


class POCDetailAPIView(mixins.DestroyModelMixin,mixins.UpdateModelMixin,generics.RetrieveAPIView):
    permission_classes=[]
    authentication_classes=[]
    serializer_class=POCSerializer


    def get_queryset(self):
        qs=Registration.objects.all()
        query=self.request.GET.get('q')
        if query is not None:
            qs=qs.objects.filter(content_icontains=query)
        return qs

    def put(self,request,*args,**kwargs):
        return self.update(request,*args,**kwargs)


    def delete(self,request,*args,**kwargs):
        return self.destroy(request,*args,**kwargs)

POC/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from .models import Registration,City
from django.views.generic import ListView, CreateView, UpdateView,DetailView,DeleteView,TemplateView
from django.urls import reverse
from django.db.models import Q
from .forms import PersonForm
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# from .forms import UserRegisterForm


# Create your views here.

# def home(request):
#     context = {
#         'peoples': Registration.objects.all()
#     }
#     return render(request, 'blog/home.html', context)



class PersonListView(LoginRequiredMixin,ListView):
    context = {
        'peoples': Registration.objects.all()
    }
    model = Registration
    template_name = 'POC/home.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'peoples'
    ordering = ['-date_posted']
    paginate_by = 3
    queryset = Registration.objects.all()


class PersonCreateView(LoginRequiredMixin,CreateView):
    model = Registration
    form_class = PersonForm
    template_name = 'POC/registration_form.html'
    # fields = ['name', 'age', 'country', 'city','zip','address']


class PostDetailView(LoginRequiredMixin,DetailView):
    model = Registration
    template_name = 'POC/registration_detail.html'

class PersonUpdateView(LoginRequiredMixin,UpdateView):

    model = Registration
    form_class = PersonForm
    # fields = ('name', 'age', 'country', 'city','zip','address')
    #success_url = reverse('person_changelist')




class PersonDeleteView(DeleteView):
    model = Registration
    # success_url = '/'
    success_url = reverse_lazy('person_changelist')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)




class HomePageView(LoginRequiredMixin,TemplateView):
    template_name = 'POC/home1.html'


class SearchResultsView(LoginRequiredMixin,ListView):
    model = Registration
    template_name = 'POC/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('p')
        querycountry = self.request.GET.get('q')
        # print(querycountry)
        querycity=self.request.GET.get('r')

        if query not in '':
            object_list = Registration.objects.filter(Q(name__icontains=query))
            print(object_list)
            if object_list == '':
                return HttpResponse('<h1>Page Not Found</h1>')
            else:
                return object_list
        if querycountry not in '':
            object_list = Registration.objects.filter(Q(country__name=querycountry))
            print(object_list)
            if object_list is None:
                print(object_list)
                return render(request, 'POC/Error.html')
            else:
                return object_list
        if querycity not in '':

            object_list = Registration.objects.filter(Q(city__name=querycity))
            if object_list == '':
                return HttpResponse('<h1>Page Not Found</h1>')
            else:
                return object_list








def load_cities(request):
    country_id = request.GET.get('country')
    print(country_id)
    cities = City.objects.filter(country_id=country_id)
    return render(request, 'POC/city_dropdown_list_options.html', {'cities': cities})

POC/templates/POC/Error.html
<h1>Error</h1>

POC/templates/POC/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <link rel="stylesheet" type="text/css" href="{% static 'POC/main.css' %}">
    <title>Loan</title>
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="#">Loan Application</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'profile' %}">Home</a>
              <a class="nav-item nav-link" href="#"></a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {%if request.user.is_superuser%}
              <a class="nav-item nav-link" href="{%url 'person_changelist'%}">List of Applications</a>
              {%endif%}
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{%url 'person_add'%}">Apply Now</a>
                <a class="nav-item nav-link" href="{%url 'logout' %}">Logout</a>

                {% else %}
                <a class="nav-item nav-link" href="{%url 'login' %}">Loan Apply Now(Login)</a>
                <a class="nav-item nav-link" href="{%url 'register' %}">Register Now</a>
                {% endif %}

                <!-- <a class="nav-item nav-link" href="{%url 'home'%}">Search</a> -->


                <a class="nav-item nav-link" href="#"></a>
                <a class="nav-item nav-link" href="#"></a>

            </div>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      {%block contentsearch%}{%endblock%}
       {% block content %}{% endblock %}
    </div>
{%block script%}{%endblock%}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

POC/templates/POC/city_dropdown_list_options.html
{%load static%}
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

POC/templates/POC/home.html
{% extends "POC/base.html" %}
{%load static%}
{%block contentsearch%}
{%if request.user.is_superuser%}
<div class="container">
  <form action="{% url 'search_results' %}" method="get">
    <input name="p" id="test" type="text" placeholder="Name">
    <input name="q"  id="test1" type="text" placeholder="Country">
    <input name="r"  id="test2" type="text" placeholder="City">
    <button type="submit" name="button" class="btn btn-success btn-sm mt-1 mb-1">Search</button>
  </form>
  <br>
<br>
{%else%}
{%endif%}
{%endblock%}


{% block content %}

{%if request.user.is_superuser%}


    <table class="table">
      <thead class="thead-dark">
    <tr>
        <th scope="col">Name</th>

        <th scope="col">Age</th>
        <th scope="col">Country</th>
        <th scope="col">City</th>
        <th scope="col">Gender</th>
        <th scope="col">Zip</th>
        <th scope="col">Address</th>
        <th scope="col">amount_required</th>
        <th scope="col">business_type</th>
        <th scope="col">phone</th>
        <th scope="col">Approve_Status</th>
        <th scope="col">Action</th>

    </tr>
    </thead>
    <tbody>
    {% for people in peoples %}
    <tr>
        <td>{{ people.name|truncatechars:9  }}</td>

        <td>{{ people.age }}</td>
          <td>{{ people.country }}</td>
            <td>{{ people.city }}</td>
              <td>{{ people.gender }}</td>
                <td>{{ people.zip }}</td>
                <td>{{ people.address|truncatechars:15 }}</td>
                <td>{{ people.amount_required }}</td>
                <td>{{ people.business_type }}</td>
                <td>{{ people.phone }}</td>
                <td>{{ people.Approve_Reject }}</td>

                <td>  <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'person_change' people.id %}">Approve Now</a>
                  <!-- <a class="btn btn-danger btn-sm mt-1 mb-1" id="deletebtn"  href="{% url 'person_delete' people.id %}">Delete</a> -->
                  <!-- {%if request.user.is_superuser%}
                  <button type="button" class="btn btn-primary" id="apvbtn">Approve</button>
                  <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'person_change' people.id %}">Approve</a>
                  {%endif%} -->
</td>

    </tr>

        </tbody>
          {% endfor %}

</table>

<div class="container">
        {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active" class="page-item" class="page-link"><span>{{ i }} <span class="sr-only">(current)</span></span></li>

      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>

    {% endif %}
  </ul>

{% endif %}
</div>
{%else%}
<center><h1>Thank You For Applying Loan<h1></center>
<center><h1>Please wait for super user to approve Your Loan<h1></center>
<center><h1>Now Please Login with super user to approve Loan<h1></center>
{%endif%}


{% endblock content %}


{%block script%}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
 <script src="{% static 'POC/list.js' %}"></script>
<script>
 $(document).on('click', '#apvbtn', function(){
   $("#apvbtn").text('Approved');

 })
 </script>
{%endblock%}

POC/templates/POC/home1.html
{% extends 'POC/base.html'%}

{%block content%}


<form action="{% url 'search_results' %}" method="get">
  <input name="q" type="text" placeholder="Search...">
  <button type="submit" name="button">Search</button>
</form>




{%endblock%}

POC/templates/POC/registration_confirm_delete.html
{% extends "POC/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="{% url 'person_delete' object.id%}">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete People Details</legend>
                <h2>Are you sure you want to delete the post "{{ object.name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'person_changelist'%}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

POC/templates/POC/registration_detail.html
{% extends "POC/base.html" %}
{% block content %}
  <article class="media content-section">

    <div class="media-body">
      <div class="article-metadata">
        Name:-<a class="mr-2" href="#">{{ object.name }}</a>
        Age:-<small class="text-muted">{{ object.age }}</small>

          <div>
            <a class="btn btn-primary" href="{% url 'person_change' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'person_delete' object.id %}">Delete</a>
          </div>

      </div>
      Country:-<h2 class="article-title">{{ object.country }}</h2>
      City:-<p class="article-content">{{ object.city }}</p>
      Zip:-<p class="article-content">{{ object.zip }}</p>
      address:-<p class="article-content">{{ object.address }}</p>
      amount_required:-<p class="article-content">{{ object.amount_required }}</p>
      business_type:-<p class="article-content">{{ object.business_type }}</p>
      phone:-<p class="article-content">{{ object.phone }}</p>

    </div>
  </article>
{% endblock content %}

POC/templates/POC/registration_form.html
{% extends 'POC/base.html' %}
{%load static%}

{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Person Details</legend>
                {{ form|crispy}}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" id="save">Post</button>
            </div>
        </form>

    </div>
{% endblock content %}
{%block script%}

  <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
<!-- <script src="{% static 'POC/jquery.min.js' %}"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- <script src="{% static 'POC/app.js' %}"></script> -->
 <!-- <script src="{% static 'POC/jquery.min.js' %}"></script> -->
<script>
$(document).ready(function($){
  $("#id_country").change(function () {
        var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        var countryId = $(this).val();  // get the selected country ID from the HTML input
console.log(countryId);

$.ajax({

    url : url,
    // type : 'GET',
    data : {
        'country': countryId

    },
    success : function(data) {
        $("#id_city").html(data);

    },
});



      });
  });
      </script>
      <script>
      $(document).ready(function(){
        // $('#id_name').click(function(){
          var str=$("#id_name").val();
          if (str=='')
          {$('#id_Approve_Reject').attr('disabled', 'disabled');}

            // alert('Hello');
            // $("#id_Approve_Reject").prop("readonly", true);


        // })
      })
</script>

 <script src="{% static 'POC/app.js' %}"></script>


{%endblock%}

POC/templates/POC/search_results.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <link rel="stylesheet" type="text/css" href="{% static 'POC/main.css' %}">
    <title>JiffyShip</title>
  </head>
  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="#">Person Details</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="#"></a>
              <a class="nav-item nav-link" href="#"></a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">

                {%if request.user.is_superuser%}
              <a class="nav-item nav-link" href="{%url 'person_changelist'%}">List of Applications</a>
              {%endif%}
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{%url 'person_add'%}">Apply Now</a>
                <a class="nav-item nav-link" href="{%url 'logout' %}">Logout</a>

                {% else %}
                <a class="nav-item nav-link" href="{%url 'login' %}">Loan Apply Now(Login)</a>
                <a class="nav-item nav-link" href="{%url 'register' %}">Register Now</a>
                {% endif %}
                <!-- <a class="nav-item nav-link" href="{%url 'home'%}">Search</a> -->
                <a class="nav-item nav-link" href="#"></a>

                <a class="nav-item nav-link" href="#"></a>
                <a class="nav-item nav-link" href="#"></a>

            </div>
          </div>
        </div>
      </nav>
    </header>
    {%block contentsearch%}
    <div class="container">
      <form action="{% url 'search_results' %}" method="get">
        <input name="p" id="test" type="text" placeholder="Name">
        <input name="q"  id="test1" type="text" placeholder="Country">
        <input name="r"  id="test2" type="text" placeholder="City">
        <button type="submit" name="button" class="btn btn-success btn-sm mt-1 mb-1">Search</button>
      </form>
      <br>
    <br>

    {%endblock%}

    <div class="container">
      <ul>
        {%if object_list %}
        <table class="table">
          <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>

            <th scope="col">Age</th>
            <th scope="col">Country</th>
            <th scope="col">City</th>
            <th scope="col">Gender</th>
            <th scope="col">Zip</th>
            <th scope="col">Address</th>
             <th scope="col">amount_required</th>
        <th scope="col">business_type</th>
        <th scope="col">phone</th>
        <th scope="col">Approve_Status</th>
        <th scope="col">Action</th>

        </tr>
        </thead>
        <tbody>

        {% for people in object_list %}
        <tr>
            <td>{{ people.name|truncatechars:9 }}</td>

            <td>{{ people.age }}</td>
              <td>{{ people.country }}</td>
                <td>{{ people.city }}</td>
                  <td>{{ people.gender }}</td>
                    <td>{{ people.zip }}</td>
                    <td>{{ people.address|truncatechars:15 }}</td>
            <td>{{ people.amount_required }}</td>
                <td>{{ people.business_type }}</td>
                <td>{{ people.phone }}</td>
                <td>{{ people.Approve_Reject }}</td>
                    <td>  <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'person_change' people.id %}">Approve Now</a>
<!--                      <a class="btn btn-danger btn-sm mt-1 mb-1" id="deletebtn"  href="{% url 'person_delete' people.id %}">Delete</a>-->
    </td>

        </tr>
        <!-- <article class="media content-section">

          <div class="media-body">
            <div class="article-metadata">

                <h3 class="mr-4" >{{ people.name }}</h3>
              Age:-<small class="text-muted">{{ people.age}}</small>
            Posted Date:-<small class="text-muted">{{ people.date_posted}}</small>
              <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'person_change' people.id %}">Update</a>
              <a class="btn btn-danger btn-sm mt-1 mb-1" id="deletebtn" href="{% url 'person_delete' people.id %}">Delete</a>
</div>
            Country:-<h2><a class="article-title" href="">{{ people.country }}</a></h2>
            City:-<p class="article-content">{{ people.city }}</p>
            Gender:-<p class="article-content">{{ people.gender }}</p>
            Zip:-<p class="article-content">{{ people.zip }}</p>
            Address:-<p class="article-content">{{ people.address }}</p>
            <div>

            </div>

          </div>
        </article> -->
      </tbody>
        {% endfor %}

</table>
{%else%}
<h1>No Data Found Please Try Again..........</h1>
{%endif%}

    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
     <script src="{% static 'POC/list.js' %}"></script>
  </body>
</html>